#!/bin/sh

action=${1:-hybrid}
delay=3

subcommand="hybrid-sleep"
case $action in
    hybrid)
        ;;
    suspend)
        subcommand="suspend"
        ;;
    hibernate)
        subcommand="hibernate"
        ;;
    lock-only)
        subcommand=''
        ;;
    *)
        echo "action '$action' not recognized; just locking and clearing"
        subcommand=''
        ;;
esac

for pid in $(pgrep Xorg)
do
    display=$(ps -o command= -p "$pid"| awk '{print $2}')
done
DISPLAY=$display xlock -mode blank&

# clear cached gpg password
echo RELOADAGENT | gpg-connect-agent

if [ -n "$subcommand" ]
then
    sleep $delay
    loginctl "$subcommand"
fi
